

<?php require 'templates/header.template.phtml'; ?>

<div class="card text-bg-danger border-dark mb-3 mt-5 w-25 mx-auto p-5 pb-2" >
    <div class="mb-3">
        <label for="formGroupExampleInput" class="form-label">ERROR!! </label>
        <label for="formGroupExampleInput" class="form-label"><?= $msgError ?></label>
    </div>
        
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a href='productos'><button type="button" class="btn btn-secondary mb-3">Atras</button></a>
    </div>
</div>

<?php require 'templates/footer.template.phtml'; ?>