<?php require 'templates/header.template.phtml'; ?>

<div class="mt-5 w-25 mx-auto" >
        <form method="POST" action="auth">
        
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" required class="form-control" id="email" name="email" aria-describedby="emailHelp">
            </div>

            <div class="form-group">
                <label for="inputPassword5" class="form-label">Contraseña</label>
                <input type="password" id="inputPassword5" class="form-control" aria-describedby="passwordHelpBlock">
                <div id="passwordHelpBlock" class="form-text">
                Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces, special characters, or emoji.
                </div>
            </div>

           
            <div class="d-grid gap-2">
            <button type="submit" class="btn btn-primary mt-3" type="button">Ingresar</button>
            </div>
        </form>
        
</div>

<?php require 'templates/footer.template.phtml'; ?>