<?php require 'templates/header.template.phtml'; ?>

<div class="mt-5 w-25 mx-auto" >
        <form method="POST" action="auth">
        
            <div class="form-group">
                <label for="user">Usuario</label>
                <input type="text" required class="form-control" id="user" name="user">
            </div>

            <div class="form-group">
                <label for="inputPassword5" class="form-label">Contraseña</label>
                <input type="password" id="inputPassword5" class="form-control" aria-describedby="passwordHelpBlock" name="password">
            </div>

           
            <div class="d-grid gap-2">
            <button type="submit" class="btn btn-primary mt-3" type="button">Ingresar</button>
            </div>
        </form>
        
</div>

<?php require 'templates/footer.template.phtml'; ?>