<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="./css/style.css">
    <title>Tu Sitio</title>
</head>
<body class='g-2 p-5'>
    <header>
        <nav class="navbar fixed-top navbar-expand-lg bg-light">
            <div class="container-fluid">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Principal</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="productos">Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Fabricantes</a>
                    </li>

                    <!--  Si la sesion no existe, se visualiza el boton de login, caso contrario mostrar 'Agregar producto / Cerrar sesion'-->
                    <?php if (!isset($_SESSION['USER_ID'])) :?>
                        <li class="nav-item">
                            <a class="nav-link" href="login">Iniciar Sesión</a>
                        </li>
                    <?php else :?>
                        <li class="nav-item">
                            <a class="nav-link" href="addProduct">Agregar producto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link logout" href="logout">Cerrar sesión</a>
                        </li>
                    <?php endif ?>
                </ul>
            </div>
        </nav>
    </header>

    <main>
    
